// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReelForge.WorkflowEngine.Data;

#nullable disable

namespace ReelForge.WorkflowEngine.Migrations
{
    [DbContext(typeof(WorkflowEngineDbContext))]
    [Migration("20260307000000_AddStepResultOutputStorageKey")]
    partial class AddStepResultOutputStorageKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReelForge.Shared.Data.Models.AgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_type");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.HasKey("Id")
                        .HasName("pk_agent_definitions");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_agent_definitions_owner_id");

                    b.ToTable("agent_definitions", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_application_users");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("application_users", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_projects_owner_id");

                    b.ToTable("projects", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.ProjectFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentSummary")
                        .HasColumnType("text")
                        .HasColumnName("agent_summary");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("SummaryStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary_status");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_project_files");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_files_project_id");

                    b.ToTable("project_files", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.ReviewScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IterationNumber")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_number");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("WorkflowExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_execution_id");

                    b.HasKey("Id")
                        .HasName("pk_review_scores");

                    b.HasIndex("WorkflowExecutionId")
                        .HasDatabaseName("ix_review_scores_workflow_execution_id");

                    b.ToTable("review_scores");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workflow_definitions");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_workflow_definitions_project_id");

                    b.ToTable("workflow_definitions");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.WorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("CurrentStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_step_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("InitiatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by_user_id");

                    b.Property<int>("IterationCount")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_count");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_executions");

                    b.HasIndex("CurrentStepId")
                        .HasDatabaseName("ix_workflow_executions_current_step_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_workflow_executions_project_id");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("ix_workflow_executions_workflow_definition_id");

                    b.ToTable("workflow_executions");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_definition_id");

                    b.Property<string>("ConditionExpression")
                        .HasColumnType("text")
                        .HasColumnName("condition_expression");

                    b.Property<string>("EdgeConditionJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("edge_condition_json");

                    b.Property<string>("FalseBranchStepOrder")
                        .HasColumnType("text")
                        .HasColumnName("false_branch_step_order");

                    b.Property<string>("InputMappingJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_mapping_json");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("LoopSourceExpression")
                        .HasColumnType("text")
                        .HasColumnName("loop_source_expression");

                    b.Property<int?>("LoopTargetStepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("loop_target_step_order");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("integer")
                        .HasColumnName("max_iterations");

                    b.Property<int?>("MinScore")
                        .HasColumnType("integer")
                        .HasColumnName("min_score");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_type");

                    b.Property<string>("TrueBranchStepOrder")
                        .HasColumnType("text")
                        .HasColumnName("true_branch_step_order");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_steps");

                    b.HasIndex("AgentDefinitionId")
                        .HasDatabaseName("ix_workflow_steps_agent_definition_id");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("ix_workflow_steps_workflow_definition_id");

                    b.ToTable("workflow_steps");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.WorkflowStepResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text")
                        .HasColumnName("error_details");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<int?>("IterationNumber")
                        .HasColumnType("integer")
                        .HasColumnName("iteration_number");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<string>("OutputStorageKey")
                        .HasColumnType("text")
                        .HasColumnName("output_storage_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.Property<Guid>("WorkflowExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_execution_id");

                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_step_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_step_results");

                    b.HasIndex("WorkflowExecutionId")
                        .HasDatabaseName("ix_workflow_step_results_workflow_execution_id");

                    b.HasIndex("WorkflowStepId")
                        .HasDatabaseName("ix_workflow_step_results_workflow_step_id");

                    b.ToTable("workflow_step_results");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.AgentDefinition", b =>
                {
                    b.HasOne("ReelForge.Shared.Data.Models.ApplicationUser", "Owner")
                        .WithMany("AgentDefinitions")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_agent_definitions__application_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.Project", b =>
                {
                    b.HasOne("ReelForge.Shared.Data.Models.ApplicationUser", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_application_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.ProjectFile", b =>
                {
                    b.HasOne("ReelForge.Shared.Data.Models.Project", "Project")
                        .WithMany("Files")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_files_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.ReviewScore", b =>
                {
                    b.HasOne("ReelForge.Shared.Data.Models.WorkflowExecution", "WorkflowExecution")
                        .WithMany("ReviewScores")
                        .HasForeignKey("WorkflowExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_scores__workflow_executions_workflow_execution_id");

                    b.Navigation("WorkflowExecution");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.WorkflowDefinition", b =>
                {
                    b.HasOne("ReelForge.Shared.Data.Models.Project", "Project")
                        .WithMany("WorkflowDefinitions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_definitions_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.WorkflowExecution", b =>
                {
                    b.HasOne("ReelForge.Shared.Data.Models.WorkflowStep", "CurrentStep")
                        .WithMany()
                        .HasForeignKey("CurrentStepId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflow_executions__workflow_steps_current_step_id");

                    b.HasOne("ReelForge.Shared.Data.Models.Project", "Project")
                        .WithMany("WorkflowExecutions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_executions_projects_project_id");

                    b.HasOne("ReelForge.Shared.Data.Models.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Executions")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_executions_workflow_definitions_workflow_definitio~");

                    b.Navigation("CurrentStep");

                    b.Navigation("Project");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.WorkflowStep", b =>
                {
                    b.HasOne("ReelForge.Shared.Data.Models.AgentDefinition", "AgentDefinition")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("AgentDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_steps_agent_definitions_agent_definition_id");

                    b.HasOne("ReelForge.Shared.Data.Models.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_steps_workflow_definitions_workflow_definition_id");

                    b.Navigation("AgentDefinition");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.WorkflowStepResult", b =>
                {
                    b.HasOne("ReelForge.Shared.Data.Models.WorkflowExecution", "WorkflowExecution")
                        .WithMany("StepResults")
                        .HasForeignKey("WorkflowExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_results_workflow_executions_workflow_executio~");

                    b.HasOne("ReelForge.Shared.Data.Models.WorkflowStep", "WorkflowStep")
                        .WithMany("Results")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_results_workflow_steps_workflow_step_id");

                    b.Navigation("WorkflowExecution");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.AgentDefinition", b =>
                {
                    b.Navigation("WorkflowSteps");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("AgentDefinitions");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.Project", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("WorkflowDefinitions");

                    b.Navigation("WorkflowExecutions");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.WorkflowDefinition", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.WorkflowExecution", b =>
                {
                    b.Navigation("ReviewScores");

                    b.Navigation("StepResults");
                });

            modelBuilder.Entity("ReelForge.Shared.Data.Models.WorkflowStep", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
